# Interval between refreshes in seconds. Default: 300
refresh_rate = 300
# In seconds how long before the fissure expires to send a notification. Default: 300
time_before_expiry_notification = 300

# Default: ["Lith", "Meso", "Neo", "Axi"]
tier_filter = [
    "Lith",
    "Meso",
    "Neo",
    "Axi",
    # "Requiem",
]

# Mission types to filter. Default: ["Disruption"]
mission_filter = [
    #"Capture",
    #"Defense",
    #"Excavation",
    #"Extermination",
    #"Interception",
    #"Mobile Defense",
    #"Rescue",
    #"Sabotage",
    #"Survival",
    #"Spy",
    #"Hijack",
    #"Assault",
    #"Defection",
    #"Infested Salvage",
    "Disruption",
    #"Sanctuary Onslaught",
    #"Free Roam",
    #"Arena",
    #"Skirmish",
    #"Orphix",
    #"Volatile",
    #"Hive",
    #"Assassination",
    #"Rush",
    #"Pursuit",
    #"Deception",
    #"Crossfire",
]

# Factions to filter. Default: ["Corpus", "Grineer", "Infested", "Orokin"]
faction_filter = [
    "Orokin",
    "Grineer",
    "Corpus",
    "Infested",
    #"Crossfire",
]

# filter for railjack fissures "void storms". Default: "Exclude"
# Possible values: you can only use one of these at a time
#   "Exclude" # Exclude those with the given value
#   "Include" # Include those with and without the given value
#   "Exclusive" # Exclude all but these values
void_storm_filter = "Exclude"
